import { Listing } from "@/types/listing";

export const MOCK_LISTINGS: Listing[] = [
  {
    id: "1",
    mlsNumber: "RX-10987412",
    address: "1240 S Ocean Blvd",
    city: "Manalapan",
    state: "FL",
    zip: "33462",
    lat: 26.5721,
    lng: -80.0492,
    area: "Manalapan",
    listPrice: 24500000,
    bedrooms: 7,
    bathrooms: 9,
    sqft: 11400,
    lotSqft: 43560,
    yearBuilt: 2019,
    propertyType: "Estate",
    waterfrontType: "Ocean",
    waterfrontFt: 210,
    waterDepthFt: 0,
    noFixedBridges: true,
    inletDistanceMi: 1.2,
    inletName: "Boynton Inlet",
    hasDock: false,
    dockLengthFt: 0,
    dockCovered: false,
    boatLift: false,
    numSlips: 0,
    photos: ["/images/listings/mock-1.jpg"],
    daysOnMarket: 14,
    status: "Active",
  },
  {
    id: "2",
    mlsNumber: "RX-10991823",
    address: "117 Commodore Dr",
    city: "Jupiter",
    state: "FL",
    zip: "33477",
    lat: 26.9342,
    lng: -80.0891,
    area: "Jupiter",
    listPrice: 8950000,
    bedrooms: 5,
    bathrooms: 6,
    sqft: 6200,
    lotSqft: 19800,
    yearBuilt: 2021,
    propertyType: "Single Family",
    waterfrontType: "Intracoastal",
    waterfrontFt: 120,
    waterDepthFt: 9,
    noFixedBridges: true,
    inletDistanceMi: 0.8,
    inletName: "Jupiter Inlet",
    hasDock: true,
    dockLengthFt: 80,
    dockCovered: false,
    boatLift: false,
    numSlips: 2,
    photos: ["/images/listings/mock-2.jpg"],
    daysOnMarket: 7,
    status: "Active",
  },
  {
    id: "3",
    mlsNumber: "RX-10978234",
    address: "2701 N Ocean Blvd",
    city: "Palm Beach",
    state: "FL",
    zip: "33480",
    lat: 26.7218,
    lng: -80.0341,
    area: "Palm Beach",
    listPrice: 32000000,
    bedrooms: 8,
    bathrooms: 11,
    sqft: 14800,
    lotSqft: 52272,
    yearBuilt: 2017,
    propertyType: "Estate",
    waterfrontType: "Ocean",
    waterfrontFt: 320,
    waterDepthFt: 0,
    noFixedBridges: true,
    inletDistanceMi: 2.1,
    inletName: "Lake Worth Inlet",
    hasDock: false,
    dockLengthFt: 0,
    dockCovered: false,
    boatLift: false,
    numSlips: 0,
    photos: ["/images/listings/mock-3.jpg"],
    daysOnMarket: 42,
    status: "Active",
  },
  {
    id: "4",
    mlsNumber: "RX-10993017",
    address: "812 Harbour Isles Ct",
    city: "North Palm Beach",
    state: "FL",
    zip: "33408",
    lat: 26.8198,
    lng: -80.0631,
    area: "North Palm Beach",
    listPrice: 5750000,
    bedrooms: 5,
    bathrooms: 5,
    sqft: 4900,
    lotSqft: 18750,
    yearBuilt: 2018,
    propertyType: "Single Family",
    waterfrontType: "Deep Canal",
    waterfrontFt: 95,
    waterDepthFt: 8,
    noFixedBridges: true,
    inletDistanceMi: 1.4,
    inletName: "Lake Worth Inlet",
    hasDock: true,
    dockLengthFt: 65,
    dockCovered: true,
    boatLift: true,
    numSlips: 2,
    photos: ["/images/listings/mock-4.jpg"],
    daysOnMarket: 21,
    status: "Active",
  },
  {
    id: "5",
    mlsNumber: "RX-10984412",
    address: "2200 S Ocean Blvd",
    city: "Highland Beach",
    state: "FL",
    zip: "33487",
    lat: 26.3891,
    lng: -80.0722,
    area: "Highland Beach",
    listPrice: 18750000,
    bedrooms: 6,
    bathrooms: 8,
    sqft: 9200,
    lotSqft: 34848,
    yearBuilt: 2020,
    propertyType: "Estate",
    waterfrontType: "Ocean",
    waterfrontFt: 185,
    waterDepthFt: 0,
    noFixedBridges: true,
    inletDistanceMi: 3.1,
    inletName: "Boca Inlet",
    hasDock: false,
    dockLengthFt: 0,
    dockCovered: false,
    boatLift: false,
    numSlips: 0,
    photos: ["/images/listings/mock-5.jpg"],
    daysOnMarket: 5,
    status: "Active",
  },
  {
    id: "6",
    mlsNumber: "RX-10971984",
    address: "501 Idlewyld Dr",
    city: "Fort Lauderdale",
    state: "FL",
    zip: "33301",
    lat: 26.1341,
    lng: -80.1092,
    area: "Fort Lauderdale",
    listPrice: 7200000,
    bedrooms: 5,
    bathrooms: 6,
    sqft: 5800,
    lotSqft: 16500,
    yearBuilt: 2016,
    propertyType: "Single Family",
    waterfrontType: "Deep Canal",
    waterfrontFt: 110,
    waterDepthFt: 10,
    noFixedBridges: true,
    inletDistanceMi: 1.8,
    inletName: "Port Everglades Inlet",
    hasDock: true,
    dockLengthFt: 90,
    dockCovered: false,
    boatLift: false,
    numSlips: 3,
    photos: ["/images/listings/mock-6.jpg"],
    daysOnMarket: 33,
    status: "Active",
  },
  {
    id: "7",
    mlsNumber: "RX-10994821",
    address: "4201 N Ocean Blvd",
    city: "Boca Raton",
    state: "FL",
    zip: "33431",
    lat: 26.3982,
    lng: -80.0762,
    area: "Boca Raton",
    listPrice: 11200000,
    bedrooms: 6,
    bathrooms: 7,
    sqft: 7400,
    lotSqft: 29185,
    yearBuilt: 2022,
    propertyType: "Estate",
    waterfrontType: "Intracoastal",
    waterfrontFt: 145,
    waterDepthFt: 7,
    noFixedBridges: true,
    inletDistanceMi: 1.1,
    inletName: "Boca Inlet",
    hasDock: true,
    dockLengthFt: 75,
    dockCovered: true,
    boatLift: false,
    numSlips: 2,
    photos: ["/images/listings/mock-7.jpg"],
    daysOnMarket: 18,
    status: "Active",
  },
  {
    id: "8",
    mlsNumber: "RX-10968732",
    address: "19 W Harbour Dr",
    city: "Palm Beach Gardens",
    state: "FL",
    zip: "33418",
    lat: 26.8782,
    lng: -80.0721,
    area: "Palm Beach Gardens",
    listPrice: 4200000,
    bedrooms: 4,
    bathrooms: 4,
    sqft: 3800,
    lotSqft: 14520,
    yearBuilt: 2015,
    propertyType: "Single Family",
    waterfrontType: "Deep Canal",
    waterfrontFt: 80,
    waterDepthFt: 6,
    noFixedBridges: false,
    inletDistanceMi: 3.2,
    inletName: "Jupiter Inlet",
    hasDock: true,
    dockLengthFt: 50,
    dockCovered: false,
    boatLift: true,
    numSlips: 1,
    photos: ["/images/listings/mock-8.jpg"],
    daysOnMarket: 60,
    status: "Active",
  },
  {
    id: "9",
    mlsNumber: "RX-10989134",
    address: "2640 Lake Dr",
    city: "Lighthouse Point",
    state: "FL",
    zip: "33064",
    lat: 26.2742,
    lng: -80.0901,
    area: "Lighthouse Point",
    listPrice: 3850000,
    bedrooms: 4,
    bathrooms: 4,
    sqft: 3400,
    lotSqft: 12632,
    yearBuilt: 2014,
    propertyType: "Single Family",
    waterfrontType: "Deep Canal",
    waterfrontFt: 75,
    waterDepthFt: 7,
    noFixedBridges: true,
    inletDistanceMi: 2.4,
    inletName: "Hillsboro Inlet",
    hasDock: true,
    dockLengthFt: 60,
    dockCovered: false,
    boatLift: true,
    numSlips: 1,
    photos: ["/images/listings/mock-9.jpg"],
    daysOnMarket: 11,
    status: "Active",
  },
  {
    id: "10",
    mlsNumber: "RX-10981902",
    address: "2150 Ibis Isle Rd",
    city: "Palm Beach",
    state: "FL",
    zip: "33480",
    lat: 26.7012,
    lng: -80.0461,
    area: "Palm Beach",
    listPrice: 16500000,
    bedrooms: 6,
    bathrooms: 8,
    sqft: 8900,
    lotSqft: 39204,
    yearBuilt: 2018,
    propertyType: "Estate",
    waterfrontType: "Intracoastal",
    waterfrontFt: 200,
    waterDepthFt: 11,
    noFixedBridges: true,
    inletDistanceMi: 1.9,
    inletName: "Lake Worth Inlet",
    hasDock: true,
    dockLengthFt: 100,
    dockCovered: false,
    boatLift: false,
    numSlips: 3,
    photos: ["/images/listings/mock-10.jpg"],
    daysOnMarket: 28,
    status: "Active",
  },
  {
    id: "11",
    mlsNumber: "RX-10995412",
    address: "1800 SE 8th St",
    city: "Fort Lauderdale",
    state: "FL",
    zip: "33316",
    lat: 26.1021,
    lng: -80.1182,
    area: "Fort Lauderdale",
    listPrice: 6100000,
    bedrooms: 5,
    bathrooms: 5,
    sqft: 5100,
    lotSqft: 17424,
    yearBuilt: 2019,
    propertyType: "Single Family",
    waterfrontType: "Deep Canal",
    waterfrontFt: 100,
    waterDepthFt: 12,
    noFixedBridges: true,
    inletDistanceMi: 2.2,
    inletName: "Port Everglades Inlet",
    hasDock: true,
    dockLengthFt: 85,
    dockCovered: true,
    boatLift: false,
    numSlips: 2,
    photos: ["/images/listings/mock-11.jpg"],
    daysOnMarket: 9,
    status: "Active",
  },
  {
    id: "12",
    mlsNumber: "RX-10977341",
    address: "10 Pelican Lane",
    city: "Tequesta",
    state: "FL",
    zip: "33469",
    lat: 26.9712,
    lng: -80.1021,
    area: "Jupiter & Tequesta",
    listPrice: 4750000,
    bedrooms: 4,
    bathrooms: 5,
    sqft: 4200,
    lotSqft: 16117,
    yearBuilt: 2016,
    propertyType: "Single Family",
    waterfrontType: "River",
    waterfrontFt: 90,
    waterDepthFt: 8,
    noFixedBridges: false,
    inletDistanceMi: 1.6,
    inletName: "Jupiter Inlet",
    hasDock: true,
    dockLengthFt: 55,
    dockCovered: false,
    boatLift: true,
    numSlips: 1,
    photos: ["/images/listings/mock-12.jpg"],
    daysOnMarket: 44,
    status: "Active",
  },
];

// Filter listings against vessel/property criteria
export function filterListings(
  listings: Listing[],
  filters: import("@/types/listing").SearchFilters
): Listing[] {
  return listings.filter((l) => {
    // Draft check — property water depth must accommodate vessel
    if (filters.vesselDraftFt > 0 && l.waterDepthFt > 0) {
      if (l.waterDepthFt < filters.vesselDraftFt) return false;
    }

    // Dock length — must fit the vessel
    if (filters.vesselLengthFt > 0 && l.hasDock) {
      if (l.dockLengthFt > 0 && l.dockLengthFt < filters.vesselLengthFt)
        return false;
    }

    // No fixed bridges
    if (filters.noFixedBridges && !l.noFixedBridges) return false;

    // Min water depth
    if (filters.minWaterDepthFt > 0 && l.waterDepthFt > 0) {
      if (l.waterDepthFt < filters.minWaterDepthFt) return false;
    }

    // Water access type
    if (filters.waterAccessTypes.length > 0) {
      const typeMap: Record<string, string[]> = {
        ocean: ["Ocean"],
        intracoastal: ["Intracoastal"],
        deep_canal: ["Deep Canal"],
        bay: ["Bay"],
        river: ["River"],
      };
      const allowed = filters.waterAccessTypes.flatMap((t) => typeMap[t] ?? []);
      if (!allowed.includes(l.waterfrontType)) return false;
    }

    // Dock required
    if (filters.dockRequired && !l.hasDock) return false;

    // Boat lift
    if (filters.boatLiftRequired && !l.boatLift) return false;

    // Price
    if (filters.priceMax > 0 && l.listPrice > filters.priceMax) return false;

    // Bedrooms
    if (filters.bedroomsMin > 0 && l.bedrooms < filters.bedroomsMin)
      return false;

    // Areas
    if (filters.areas.length > 0 && !filters.areas.includes(l.area))
      return false;

    return true;
  });
}

export function formatPrice(price: number): string {
  if (price >= 1_000_000) {
    const m = price / 1_000_000;
    return `$${m % 1 === 0 ? m.toFixed(0) : m.toFixed(1)}M`;
  }
  return `$${price.toLocaleString()}`;
}
